### ISSUE TITLE
不在域根目录图片无法加载

### ISSUE THREAD

**Issue by w311ang** [MeowCat-Studio/Meow-Chat#2]
![Screenshot_20201122-013858](https://user-images.githubusercontent.com/30381083/99883601-81714280-2c63-11eb-9c90-bffb82dd2dc1.png)
![Screenshot_20201122-013954](https://user-images.githubusercontent.com/30381083/99883633-acf42d00-2c63-11eb-93e9-93082951d347.png)

**Comment by MlgmXyysd** [comment]
绝对路径造成的问题，有时间重整一遍

**Comment by w311ang** [comment]
> 绝对路径造成的问题，有时间重整一遍

已经被我修好了，不敢pr

**Comment by w311ang** [comment]
https://github.com/w311ang/Meow-Chat-edited 这项目已经被我爆改了

**Comment by w311ang** [comment]
#4
